### ISSUE TITLE
detach volume failure

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn-manager#25]
ERRO[405331] detaching volume: controller failed, volume 'dockercon_test2': exit status 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7632ab]

goroutine 270 [running]:
github.com/rancher/longhorn-manager/manager.(*volumeManager).stopMonitoring(0xc4201dd1d0, 0x0)
	/go/src/github.com/rancher/longhorn-manager/manager/manager.go:245 +0x6b
github.com/rancher/longhorn-manager/manager.(*volumeManager).doDetach(0xc4201dd1d0, 0x0, 0xf, 0x0)
	/go/src/github.com/rancher/longhorn-manager/manager/manager.go:352 +0x50
github.com/rancher/longhorn-manager/manager.(*volumeManager).Detach(0xc4201dd1d0, 0xc4202fdd70, 0xf, 0x10, 0x0)
	/go/src/github.com/rancher/longhorn-manager/manager/manager.go:348 +0x7e
github.com/rancher/longhorn-manager/manager.monitor(0x10fd040, 0xc42024c6c0, 0xc4202bc580, 0x10fe940, 0xc4201dd1d0, 0xc4202d9f20)
	/go/src/github.com/rancher/longhorn-manager/manager/monitor.go:74 +0x2d4
created by github.com/rancher/longhorn-manager/manager.Monitor.func1
	/go/src/github.com/rancher/longhorn-manager/manager/monitor.go:42 +0xc3

**Comment by yasker** [comment]
Two things are wrong here:
1. Detach/Delete should be idempotent. The second call passing nil volume for deletion, result in NPE.
2. There is a race condition between normal Delete operation and monitor thread. Monitor thread didn't stop fast enough and still report volume failure after the volume has been deleted, which result in the second call of Detach.
